### ISSUE TITLE
Remove Excess Docker-Compose Configuration

### ISSUE THREAD

**Issue by wesleyboar** [TACC/Core-CMS-Custom#222]
## Overview

We should be able to remove `postgres` and `elasticsearch` from Docker Compose configuration.

## To Do

1. Review https://github.com/TACC/Core-CMS-Custom/pull/184#discussion_r1313265971, https://github.com/TACC/Core-CMS-Custom/pull/184#discussion_r1313275723, https://github.com/TACC/Core-CMS-Custom/pull/184#discussion_r1313277366, and https://github.com/TACC/Core-CMS-Custom/pull/184#discussion_r1313279485.
2. Determine which changes are safe and how to do them.
3. Do it, and test each project.

**Comment by wesleyboar** [comment]
**Is this how I do that?**

1. Sync container `docker-compose.dev.yml` (from Core-CMS) to local files as `docker-compose.core-cms.yml`:

    **`docker-compose.dev.yml`**
    ```
        volumes:
          - ./docker-compose.core-cms.yml:/code/docker-compose.dev.yml
    ```

2. Make `postgres` and `elasticsearch` services extend `docker-compose.core-cms.yml`:

    **`docker-compose.dev.yml`**
    ```
      postgres:
        extends:
          file: ../docker-compose.core-cms.yml
          service: postgres

      elasticsearch:
        extends:
          file: ../docker-compose.core-cms.yml
          service: elasticsearch
    ```
